services:
  librarian-api:
    hostname: librarian-api
    container_name: librarian-api
    image: librarian-api:latest
    build:
      context: ./backend
    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - ./backend/src:/app/src
      - ./backend/db:/app/db
      - ./dev-config/api/settings.yaml:/app/config/settings.yaml:ro
    env_file: .env
    depends_on:
      librarian-migrate:
        condition: service_completed_successfully

  librarian-service:
    hostname: librarian-service
    container_name: librarian-service
    image: librarian-service:latest
    build:
      context: ./backend
    entrypoint: [run-service]
    volumes:
      - ./backend/src:/app/src
      - ./backend/db:/app/db
      - ./dev-config/service/settings.yaml:/app/config/settings.yaml:ro
    env_file: .env
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      librarian-migrate:
        condition: service_completed_successfully

  librarian-web:
    hostname: librarian-web
    container_name: librarian-web
    image: librarian-web:dev
    build:
      context: ./frontend
      target: dev
    command: --host librarian-web
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public

  librarian-migrate:
    hostname: librarian-migrate
    container_name: librarian-migrate
    image: librarian-migrate:latest
    build:
      context: ./backend
    entrypoint: [migrate]
    command: [up]
    volumes:
      - ./backend/src:/app/src
      - ./backend/db:/app/db
      - ./dev-config/service/settings.yaml:/app/config/settings.yaml:ro
    depends_on:
      librarian-postgres:
        condition: service_healthy

  librarian-postgres:
    hostname: librarian-postgres
    container_name: librarian-postgres
    image: librarian-postgres:latest
    build:
      context: ./backend/db
    environment:
      - POSTGRES_DB=librarian
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin-pass
    volumes:
      - ./.container_data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d librarian"]
      start_period: 10s
      start_interval: 1s
      interval: 5s
      timeout: 1s
      retries: 5
