service:
  autoreload: true

database:
  user: admin
  password: admin-pass
  host: librarian-postgres
  port: 5432
  name: librarian

google_oauth:
  # This is an adhoc, dev encryption key
  token_encryption_key: 6DERvXJRIJQChZY06cGR1A0Aj8o0CS0zh40H7wtv-kU=

blob_extractor:
  concurrent_workers: 3

  ollama_host: http://librarian-ollama:11434
  llm_model: anthropic:claude-haiku-4-5
  llm_pdf_mode: binary

node_extractor:
  concurrent_workers: 3
  ollama_host: http://librarian-ollama:11434

http_client:
  timeout: 900
